version: 2

sphinx:
   configuration: docs/conf.py

formats:
  - pdf

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.12'
  jobs:
    install:
      - python -m pip install --no-cache-dir --use-pep517 .[docs]
